services:
  - type: web
    name: silver3premiumsmartbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ACCUWEATHER_API_KEY
        sync: false
      - key: GIPHY_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
    # Ustawienia dla web service
    healthCheckPath: /health
    autoDeploy: true
    # Timeouty i ustawienia dla Render
    healthCheckTimeout: 300
    # Dodatkowe ustawienia portów
    port: 10000
    # Ustawienia dla lepszej stabilności
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1" 